### ISSUE TITLE
Update oui.txt file

### ISSUE THREAD

**Issue by greaterthanstar** [calebmadrigal/trackerjacker#21]
I have many missing vendor fields in my `wifi_mal.yml`. The `oui.txt` file included with the project is out of date and in a custom format. Let's say I run `airodump-ng-oui-update` to download the latest file to `/var/lib/ieee-data//oui.txt`. What commands would I run to convert it to the `MAC=VENDOR` format used by trackerjacker?

**Comment by greaterthanstar** [comment]
Answering my own question here.. I may do a PR to merge this newer file into the system. It'd be nice if there was a command line option to do this tho. 

In Kali you can use the aircrack-ng auto-updater to easily download an updated oui.txt file to  /var/lib/ieee-data/oui.txt..
`airodump-ng-oui-update`
` cp /var/lib/ieee-data/oui.txt ~/oui.txt`
`egrep '^(\w{6})\s*\(.*?\)\s+(.*?)$' ~/oui.txt | sed -r 's/^(\w{6})\s*\(.*?\)\s+(.*?)$/\1=\2/' > ~/fixedout.txt`
`cp ~/fixedout.txt /usr/local/lib/python3.7/dist-packages/trackerjacker/oui.txt`

**Comment by calebmadrigal** [comment]
That sounds like a good PR.

**Comment by greaterthanstar** [comment]
Created! https://github.com/calebmadrigal/trackerjacker/pull/22

**Comment by calebmadrigal** [comment]
Merged https://github.com/calebmadrigal/trackerjacker/pull/22. Thanks @greaterthanstar!
